#!/bin/bash

URI="http://build.timetoknow.com:8080/view/int%20monitoring/?fullscreen=true"
PIPELINES_URL="http://build.timetoknow.com:8080/view/int%20monitoring/api/json?page=1&component=1&fullscreen=true"
OUTPUT=~/int_monitor.html
STATUS_COLOR="#00C900"

wget $PIPELINES_URL -O $OUTPUT -q -T 1
if [[ $? -eq 0 ]]; then
	LAST_PIPELINE_RESULT=$(grep -oP '(?<=type":").*?(?=")' $OUTPUT | head -1)

	if [[ "$LAST_PIPELINE_RESULT" == "FAILED" ]]; then
		STATUS_COLOR="#C90000"
	elif [[ "$LAST_PIPELINE_RESULT" == "RUNNING" ]]; then
		STATUS_COLOR="#8989ff"
	fi	
else
	STATUS_COLOR="#C90000"
fi

echo " Mon"
echo # Empty short text

# color
echo $STATUS_COLOR

if [[ $BLOCK_BUTTON -eq 1 ]]; then
	yad --html --uri=$URI --title="Int Monitor" --width=1800 --height=700 --button=gtk-ok 
fi

